modLoader="javafml"
loaderVersion="[47,)"
license="Lily License v1.1"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="assets/cursed-spawners/icon.png"
authors="Provismet (original mod); unofficial Forge 1.20.1 backport"
displayTest="MATCH_VERSION"
description='''
UNOFFICIAL MODIFIED VERSION of Cursed Spawners by Provismet.
Backported from the original Fabric/Quilt Minecraft 1.21 release to native Forge Minecraft 1.20.1.
Original project: https://github.com/Provismet/Cursed-Spawners
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47.4.16,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
